version: '3.2'
services:
  wordpress:
    build:
      context: wordpress/
    privileged: true
    depends_on:
      - wordpress-db
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      - VIRTUAL_HOST=blog.owens-netsec.com
      - LETSENCRYPT_HOST=blog.owens-netsec.com
      - LETSENCRYPT_EMAIL=simonowens157@gmail.com
      - VIRTUAL_PORT=80

  wordpress-db:
    build: mysql/
    privileged: true
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

networks:
  default:
    external:
      name: webproxy
